# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator

# Mouse mode
set -g mouse on

# All the colors
set -g default-terminal "screen-256color"

# Start counting pane and window number at 1
set -g base-index 1
setw -g pane-base-index 1

is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"



# Hook to run a command when a new session is created
set-hook -g session-created 'run-shell "if [ #{session_name} = jupyter ]; then tmux send-keys -t #{session_name} '\''cd ~/Drafts && jupyter lab --no-browser > ~/.local/share/jupyter.log 2>&1'\'' C-m; tmux new-window; fi"'

# Hook to run a command when a new session is created
set-hook -g session-created 'run-shell "if [ #{session_name} = marimo ]; then tmux send-keys -t #{session_name} '\''cd ~/Drafts && marimo edit --headless --port 8888 > ~/.local/share/marimo.log 2>&1'\'' C-m; tmux new-window; fi"'

# For fox
if-shell '[ "$(hostname)" = "fox" ]' {
}

# For machine B
if-shell '[ "$(hostname)" = "machine-B-hostname" ]' {
  set-hook -g session-created 'run-shell "if [ #{session_name} = jupyter ]; then tmux send-keys -t #{session_name} '\''cd ~/notebooks/machineB && jupyter lab --no-browser > /tmp/jupyter.log 2>&1'\'' C-m; tmux new-window; fi"'
}


#set-hook -g after-new-session 'run-shell "
#if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
#fi
#"'

#bind-key -t copy-mode-vi 'C-h' select-pane -L
#bind-key -t copy-mode-vi 'C-j' select-pane -D
#bind-key -t copy-mode-vi 'C-k' select-pane -U
#bind-key -t copy-mode-vi 'C-l' select-pane -R
#bind-key -t copy-mode-vi 'C-\' select-pane -l
